### PR TITLE
Added Asp.Net Core 3.1 support, fixed a NullReference exception

### PR DESCRIPTION
**Pull request by ghost**
- Added Asp.Net Core 3.1 support.
- Added .Net Standard 2.1 support.
- Fixed a NullReference exception bug when RazorViewEngine not found.

### CODE REVIEW

**Comment by pofider** [comment]
Thank you for your work.

What is the point of updating netstandard to 2.1?
From what I've read, the lower value that works for you, better.
I see for example that [json.net here](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Newtonsoft.Json.csproj#L3) also stays with standard 2.0

**Comment by ghost** [comment]
.Net Core 3.1 is LTS. .Net standard 2.1 has a lot of improvements [(see announcement here)](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/). Also, it has [(backward compatibility)](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support). And it uses [C# 8](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8) which adds a ton of features and enhancements. In special, this PR contains the "[using declaration](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations)" syntax.

**Comment by pofider** [comment]
Thanks. I get that. However, with changing to .net standard 2.1 we cut support to the .net core 2.1 which is still actively supported by Microsoft for another whole year.

Isn't this a bad trade-off to cut out .net core 2.1 apps and get instead language features in this very small library?

**Comment by pofider** [comment]
Thank you

**Pull request merged**
